kiegroup/droolsjbpm-knowledge

kie-api/src/main/java/org/kie/api/runtime/rule/RuleRuntime.java
I know there is no obligation to document unchecked exceptions, but here the doc was explicitly saying something different.
Ref https://issues.jboss.org/browse/DROOLS-579
=> [DROOLS-579] Wrong doc for RuleRuntime.getQueryResults - throwing RuntimeException instead of empty results

kie-internal/src/main/java/org/kie/internal/runtime/manager/RuntimeManagerRegistry.java
Second option is to define the `registeredManager` as `Map` instead of `ConcurrentHashMap` (the implementation will of course stay the same). With proper comment (to make sure it won't get changed back), that should work as well.
=> [DROOLS 840] workaround JDK 8 compile compatibility issue

kie-internal/src/main/java/org/kie/internal/command/ExtendedKieCommands.java
In droolsjbpm/drools#464 there was added possibility to create clear commands in CommandFactoryServiceImpl. This PR reflects this change into command factory interface.
Added to ExtendedKieCommands according to https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/95
=> Adding possibility to create Clear commands using CommandFactory

kie-api/src/main/java/org/kie/api/runtime/StatelessKieSession.java
Updated the JavaDoc in StatelessKieSession so it now shows how to use the KieCommands public-api instead of the CommandFactory internal-api to create Commands.
=> [DROOLS-1042] update JavaDoc in StatelessKieSession

kie-api/pom.xml
* no need for the profile anymore as Java 8+ is
now required for the repo to build
=> kie-api: move the revapi-check into default build

kie-internal/pom.xml
* only guided-dtable support for now. Rest (pmml, scorecards) will be coming
in future
@mariofusco could you please review?
=> [BZ-1312164] optionally osgi-import drools-wb-models-guided-dtable package

kie-api/pom.xml, kie-internal/pom.xml
Depends on:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/183
=> [DROOLS-1129] consistent OSGi Bundle-SymbolicName for all jars

kie-internal/src/main/java/org/kie/internal/builder/InternalKieBuilder.java
This PR is required for LiveSpark, where we require the ability to prevent client-side classes with GWT dependencies from being compiled.
=> Add interface for filtering Java classes out of KIE project builds.

kie-api/src/build/revapi-config.json, kie-api/src/main/java/org/kie/api/management/GenericKieSessionMonitoringMXBean.java, kie-api/src/main/java/org/kie/api/management/KieSessionMonitoringMXBean.java, kie-api/src/main/java/org/kie/api/management/StatelessKieSessionMonitoringMXBean.java
MBean currently provide statistics as a String property list for
historical reasons.
As JMX supports Table as Maps, rework them as proper JMX Table support.
=> DROOLS-1237 MBean statistics from String property to proper JMX table.

kie-api/pom.xml
Use the version property for the latest Kie release in revapi-maven-plugin
when checking API compatibility.
Please also see : https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/270
=> RHBRMS-2552 Use version property for Kie release.

kie-api/pom.xml, kie-internal/pom.xml
- both these javadoc jars are used by Drools during standard build,
so it needs to exist .m2 even for non-full builds
=> kie-[api|internal]: always build the javadoc jar

kie-internal/src/main/java/org/kie/internal/utils/ChainedProperties.java
The ChainedProperties utility has a caching setting that will cache the classpath discovery of property resource - but not the parsing of these resources.
This utility is a hot spot for the initialization of runtime environments - caching the parsed properties instead of the resource url will improve runtime performance.
Changing the caching strategy will make hot changes to classpath property resources impossible. File based property files could be made safe cacheable by investigating file metadata and only read if changed.
=> DROOLS-1443 change caching to case properties instead of urls

kie-api/src/build/revapi-config.json
Hi,
this PR is related to droolsjbpm/droolsjbpm-build-bootstrap#393. Revapi config JSON file was divided into filter and ignores parts.
Marian
=> Split revapi configuration into filter and ignores

kie-api/src/build/revapi-config.json
Hi, @psiroky,
this is only a minor change to the revapi-config.json file, since these files are no more only on master branch, but on 7.0.x as well.
Marian
=> Change revapi-config.json comment to be more general

kie-api/src/main/java/org/kie/api/builder/ReleaseId.java
Related:
https://github.com/kiegroup/drools/pull/1342
https://github.com/AppFormer/uberfire/pull/760
=> AF-558: adjust to the renamed ReleaseId from AppFormer

kie-api/src/main/java/org/kie/api/marshalling/ObjectMarshallingStrategy.java
As a result of https://github.com/kiegroup/drools/pull/1354, a new approach to solve the issue as suggested by mswiderski
=> [DROOLS-1629] Allow backward compatibility without breaking interface

kie-internal/src/main/java/org/kie/internal/jaxb/StringKeyObjectValueMapXmlAdapter.java, kie-internal/src/main/java/org/kie/internal/jaxb/StringKeyStringValueMapXmlAdapter.java, kie-internal/src/main/java/org/kie/internal/query/ExtendedParametrizedQueryBuilder.java
JDK9 javadoc chokes on these, even thought it works with JDK8.
=> [DROOLS-1780] escape invalid chars in javadoc

kie-api/pom.xml
Please see this [PR](https://github.com/kiegroup/kie-soup/pull/8) for general discussion.
=> AF-593+: Move uberfire-maven-utils to kie-soup.

kie-api/src/build/revapi-config.json
Hi, @psiroky,
see kiegroup/droolsjbpm-build-bootstrap/pull/595 for more information.
=> Revapi checks against 7.0.0.Final now

kie-api/pom.xml
Package "org.drools.core.fluent.impl" is not imported by kie-api. This package is used in ExecutableRunner interface.
=> [DROOLS-2885] Add missing OSGI import in kie-api

kie-api/src/build/revapi-config.json, kie-api/src/main/java/org/kie/api/runtime/builder/ExecutableBuilder.java, kie-api/src/main/java/org/kie/api/runtime/builder/KieContainerFluent.java
Exposed two new method in fluent API to support pluggable external KieContainer and KieSession customization before creation
@Rikkola @jsoltes
PRs:
https://github.com/kiegroup/drools/pull/2036
https://github.com/kiegroup/droolsjbpm-knowledge/pull/323
https://github.com/kiegroup/drools-wb/pull/920
=> [DROOLS-2906] Implement scenario runner (backend)

kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/archetype-resources/__artifactId__.xml
@mswiderski you can specify now -DruntimeStrategy=PER_CASE for case projects. There is no specific "is case project" flag for this archetype, but in bootstrapjbpm you should know if this needs to be set or not given the kjar settings (kjar, dkjar).
=> JBPM-7892 - fix runtime strategy for case project in archetype

kie-api/src/build/revapi-config.json, kie-api/src/main/java/org/kie/api/internal/runtime/KieRuntimeService.java, kie-api/src/main/java/org/kie/api/runtime/KieRuntimeFactory.java
1. Change public interface of the KieRuntimeService to require a KieBase instead of a KieRuntime. 
2. Provide a new, public API to tie a KieBase to a factory of runtime
The (2) really is trivial. Almost a oneliner.
@mariofusco @tarilabs
=> DROOLS-3379: RuntimeService API should not require a KieRuntime to create an instance

kie-internal/src/main/java/org/kie/internal/command/RegistryContext.java
As discussed I moved RegistryContext to kie-internal end updated usages.
@mariofusco @kkufova 
PR list:
https://github.com/kiegroup/droolsjbpm-knowledge/pull/348
https://github.com/kiegroup/drools/pull/2174
https://github.com/kiegroup/drools-wb/pull/1012
https://github.com/kiegroup/jbpm/pull/1387
https://github.com/kiegroup/droolsjbpm-integration/pull/1657
=> [DROOLS-3177] Moved RegistryContext to kie-internal

kie-api/src/build/revapi-config.json, kie-internal/src/main/java/org/kie/internal/builder/fluent/ContextFluent.java, kie-internal/src/main/java/org/kie/internal/builder/fluent/DataSourceFluent.java, kie-internal/src/main/java/org/kie/internal/builder/fluent/ExecutableBuilder.java, kie-internal/src/main/java/org/kie/internal/builder/fluent/KieContainerFluent.java, kie-internal/src/main/java/org/kie/internal/builder/fluent/KieSessionFluent.java, kie-internal/src/main/java/org/kie/internal/builder/fluent/ProcessFluent.java, kie-internal/src/main/java/org/kie/internal/builder/fluent/RuleFluent.java, kie-internal/src/main/java/org/kie/internal/builder/fluent/RuleUnitExecutorFluent.java, kie-internal/src/main/java/org/kie/internal/builder/fluent/RuleUnitFluent.java, kie-internal/src/main/java/org/kie/internal/builder/fluent/Scope.java, kie-internal/src/main/java/org/kie/internal/builder/fluent/TaskFluent.java, kie-internal/src/main/java/org/kie/internal/builder/fluent/TimeFluent.java, kie-internal/src/main/java/org/kie/internal/builder/fluent/WorkItemManagerFluent.java
As discussed, this PR move to kie-internal the fluent API because it is still experimental
@mariofusco @mdproctor @kkufova 
PRs list:
https://github.com/kiegroup/droolsjbpm-knowledge/pull/349
https://github.com/kiegroup/drools/pull/2177
https://github.com/kiegroup/drools-wb/pull/1016
https://github.com/kiegroup/droolsjbpm-integration/pull/1661
=> [DROOLS-3401] Moved Fluent API to kie-internal

kie-internal/pom.xml, kie-internal/src/main/java/org/kie/internal/runtime/manager/deploy/DeploymentDescriptorIO.java, kie-internal/src/main/java/org/kie/internal/runtime/manager/deploy/DeploymentDescriptorImpl.java, kie-internal/src/main/java/org/kie/internal/runtime/manager/deploy/DeploymentDescriptorManager.java, kie-internal/src/main/java/org/kie/internal/runtime/manager/deploy/TransientNamedObjectModel.java, kie-internal/src/main/java/org/kie/internal/runtime/manager/deploy/TransientObjectModel.java, kie-internal/src/main/resources/deployment-descriptor.xsd, kie-internal/src/test/java/org/kie/internal/runtime/manager/deploy/DeploymentDescriptorTest.java, kie-internal/src/test/java/org/kie/internal/runtime/manager/deploy/JaxbMarshalingTest.java, kie-internal/src/test/resources/deployment/deployment-descriptor-defaults-and-ms.xml, kie-internal/src/test/resources/deployment/deployment-descriptor-defaults.xml, kie-internal/src/test/resources/deployment/empty-descriptor.xml, kie-internal/src/test/resources/deployment/partial-deployment-descriptor.xml
Add three classes + the xsd, including testing to the kie-internal-api
=> [JBPM-5215] Reuse deployment descriptor classes from common jBPM module

kie-api/src/build/revapi-config.json, kie-api/src/main/java/org/kie/api/internal/assembler/KieAssemblerService.java, kie-api/src/main/java/org/kie/api/internal/assembler/KieAssemblers.java, kie-api/src/main/java/org/kie/api/internal/assembler/ProcessedResource.java, kie-api/src/main/java/org/kie/api/internal/io/ResourceTypePackage.java, kie-api/src/test/java/org/kie/api/internal/utils/MockAssemblersImpl.java, kie-api/src/test/java/org/kie/api/internal/utils/MockChildAssemblerService.java, kie-internal/pom.xml, kie-internal/src/main/java/org/kie/internal/builder/AssemblerContext.java, kie-internal/src/main/java/org/kie/internal/services/KieAssemblersImpl.java, kie-internal/src/main/java/org/kie/internal/services/KieWeaversImpl.java
-  better support for jBPM and generic runtimes
Must be merged with:
- https://github.com/kiegroup/drools/pull/2181
- https://github.com/kiegroup/jbpm/pull/1393
Changes
======
This does not move the APIs to `kie-internal` yet, because it's not a zero-impact change. Will possibly do with a later PR
- Kie{Assemblers,Weavers} are the services through which an {assembler,weaver} service is looked up, by type. Current API is `KieAssembler.getAssemblers()` which return a `Map<ResourceType, Assembler>` (similar for KieWeavers). This is bad because it exposes an internal implementation detail (the Map). Instead, instead we now expose methods that mimic the signature of an `{Assembler,Weaver}Service`, dispatching to the correct delegate (if any).
E.g.: assume you have ResourceType BPMN2, and want …
=> DROOLS-3355: Improve Assembler/Weaver API

kie-api/src/main/java/org/kie/api/pmml/PMML4Result.java
because of the way JSON is marshalled/unmarshalled
=> RHPAM-1875 Fix required 

kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/archetype-resources/src/main/java/DefaultWebSecurityConfig.java
@tsurdilo @MarianMacik could you please review and maybe test it? To test you need to generate an app that is
- version 7.17 to try with SpringBoot 1.5.x
- version 7.18 or higher to try with SpringBoot 2.1.x
had to move back to no op password encoder to make it work on both versions.
=> RHPAM-2017 - Compilation error in Spring Boot business application

kie-internal/src/main/java/org/kie/internal/builder/fluent/RuleFluent.java
This PR enable additional parameters to rule test scenarios. It is possible now to specify KieSession name and RuleFlowGroup/AgendaGroup
+
It contains a small fix on Test Coverage report lifecycle
https://issues.jboss.org/browse/DROOLS-3840
@gitgabrio @Rikkola @jomarko 
PRs list:
- https://github.com/kiegroup/drools-wb/pull/1137
- https://github.com/kiegroup/drools/pull/2347
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/383
=> [DROOLS-3840] Extend test scenario runner to support additional parameters

kie-api/src/main/java/org/kie/api/pmml/PMMLRequestData.java
Adding a paramater to a PMMLRequestData object now replaces a parameter with the same name.
=> RHPAM-2064 Guided Score card rules not executed via test scenario

kie-internal/src/main/java/org/kie/internal/definition/rule/InternalRule.java
This PR contains backend support and UI changes to calculate test coverage KPIs for rules
NOTE: now if a rule has been executed multiple times in the same scenario, the last section of the report (rules executed for each scenario) will show also this number. I.e. `com.rule (3)`
@kkufova @Rikkola @yesamer 
PRs list:
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/396
- https://github.com/kiegroup/drools/pull/2471
- https://github.com/kiegroup/drools-wb/pull/1197
=> [DROOLS-3743] Implement Test scenario coverage report for RULE

kie-internal/src/main/java/org/kie/internal/ruleunit/RuleUnitDescription.java, kie-internal/src/main/java/org/kie/internal/ruleunit/RuleUnitVariable.java
RuleUnitDescription interface returns `Method`s; in Kogito we need a way to abstract over class definitions so that a RuleUnit can be materialized at later stages of the compilation process.
with this JIRA, we introduce an abstraction over RuleUnitDescription, so that different implementations can be provided. The default implementation is reflective (uses Methods), but a non-reflective implementation will be allowed.
see https://github.com/kiegroup/drools/pull/2673
=> DROOLS-4837: Abstract reflective accesses from RuleUnitDescription

kie-internal/src/main/java/org/kie/internal/ruleunit/RuleUnitComponentFactory.java
add RuleUnitDescription createRuleUnitDescription( KiePackage pkg, String ruleUnitSimpleName ); implementation should be a no-op because it is only used in Kogito
=> DROOLS-4895 Backport RuleUnitComponentFactory#createRuleUnitDescription( KiePackage, String );

kie-api/src/main/java/org/kie/api/runtime/manager/audit/NodeInstanceLog.java
added a new event log for node instance to be able to tell the different when
a node is left or aborted
=> [RHPAM-2774] AchievedAtDate for milestone is not preserved when case is reopen

kie-api/src/build/revapi-config.json, kie-api/src/main/java/org/kie/api/task/model/TaskSummary.java, kie-internal/src/main/java/org/kie/internal/task/api/model/TaskEvent.java
Adding getCorrelationKey and getProcessType to TaskSummary interface
=> [JBPM-9195] Case traceability from a Task Instance

kie-internal/src/main/java/org/kie/internal/conf/AlphaRangeIndexThresholdOption.java
**JIRA**:
https://issues.redhat.com/browse/DROOLS-5757
https://github.com/kiegroup/drools/pull/3186
<details>
<summary>
</summary>
</details>
=> [DROOLS-5757] Default value for alpha node range index threshold

kie-internal/src/main/java/org/kie/internal/task/api/TaskInstanceService.java
JIRA: [link] (https://issues.redhat.com/browse/JBPM-9427)
cherry picked from https://github.com/kiegroup/droolsjbpm-knowledge/commit/9cb55b026dc2d1fadb33840e91847cf4135dbb0b
=> (QE) [7.44.x] [JBPM-9427] IllegalArgumentException when task is skipped in afterTaskAddedEvent

kie-api/src/main/java/org/kie/api/definition/process/Node.java, kie-api/src/main/java/org/kie/api/definition/process/NodeType.java
Adding getNodeType to Node interface.
NodeType is an enumeration containing all posible node types
Merge with 
[jbpm:1804](https://github.com/kiegroup/jbpm/pull/1804)
**JIRA**: 
[JBPM-9465]( https://github.com/fjtirado/droolsjbpm-knowledge/pull/new/JBPM-9465)
=> [JBPM-9465] Add support for using the public API to retrieve a node type

kie-internal/src/main/java/org/kie/internal/runtime/manager/InternalRegisterableItemsFactory.java
Adding addProcesEvent (Class) and addProcessEvent (ProcessEventListener)
to RegistrableItemsFactory
**JIRA**:
[JBPM-9504](https://issues.redhat.com/browse/JBPM-9504)
https://github.com/kiegroup/droolsjbpm-integration/pull/2339
https://github.com/kiegroup/jbpm/pull/1818
=> [JBPM-9504] Exception on unDeploy at KafkaServerExtension

kie-api/src/main/java/org/kie/api/io/ResourceType.java
adds the DRLX resource type
**JIRA**:
- https://issues.redhat.com/browse/DROOLS-5997
**referenced Pull Requests**:
- https://github.com/kiegroup/drools/pull/3327
=> DROOLS-5997 Initial DRLX support 

kie-internal/src/main/java/org/kie/internal/runtime/manager/audit/query/AuditDateDeleteBuilder.java, kie-internal/src/main/java/org/kie/internal/runtime/manager/audit/query/AuditDeleteBuilder.java
Adding new maxRecordsPerTransaction parameter to builder interface
**JIRA**:
[link](https://issues.redhat.com/browse/JBPM-9579)
https://github.com/kiegroup/jbpm/pull/1853
https://github.com/kiegroup/droolsjbpm-integration/pull/2390
=> [JBPM-9579] Adding a pagination parameter to LogCleanupCommand

kie-api/src/build/revapi-config.json, kie-api/src/main/java/org/kie/api/internal/assembler/KieAssemblerService.java, kie-api/src/main/java/org/kie/api/internal/assembler/KieAssemblers.java, kie-api/src/main/java/org/kie/api/io/ResourceWithConfiguration.java, kie-api/src/test/java/org/kie/api/internal/utils/MockAssemblersImpl.java, kie-api/src/test/java/org/kie/api/internal/utils/MockChildAssemblerService.java, kie-internal/src/main/java/org/kie/internal/io/ResourceWithConfigurationImpl.java, kie-internal/src/main/java/org/kie/internal/services/KieAssemblersImpl.java
See https://issues.redhat.com/browse/DROOLS-6048
Scope of this PR is to enforce/clarify the "before rules/after rules" semantic introduced by DROOLS-5950.
In detail:
1) addResourceAfterRules and addResourcesAfterRules method have been defined/implemented
2) the above have taken place of the previous addResource / addResources ones
3) addResource / addResources have been deprecated
4) inside KieAssemblerService, all the methods have a default implementation, since no-one of them is actually required anymore
@tarilabs @evacchi FYI
Required by https://github.com/kiegroup/drools/pull/3405
=> [DROOLS-6048] Enforcing before rules/after rules semantics for assemblers

kie-internal/src/main/java/org/kie/internal/pmml/PMMLImplementationsUtil.java, kie-internal/src/test/java/org/kie/internal/pmml/PMMLImplementationsUtilTest.java
See https://issues.redhat.com/browse/DROOLS-5862
This PR change the logic of PMML selection, defaulting to Trusty one
Bundle with:
https://github.com/kiegroup/drools/pull/3414
https://github.com/kiegroup/droolsjbpm-integration/pull/2409
=> [DROOLS-5862] Defaulting PMML to Trusty implementation

kie-internal/src/main/java/org/kie/internal/runtime/manager/deploy/DeploymentDescriptorManager.java, kie-internal/src/main/java/org/kie/internal/runtime/manager/deploy/DeploymentDescriptorMerger.java, kie-internal/src/test/java/org/kie/internal/runtime/manager/deploy/DeploymentDescriptorMergerTest.java
Adding possibility of several default descriptors
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9699)
https://github.com/kiegroup/droolsjbpm-integration/pull/2455
https://github.com/kiegroup/jbpm/pull/1918
=> [JBPM-9699] Register workitemhandler when Kafka extension is enabled

kie-internal/src/main/java/org/kie/internal/utils/KieHelper.java
Write `KieModuleModel` to `KieFileSystem` before building `KieBuilder` in `KieHelper`. This was causing the verification to fail, but the `KieContainer` to be built successfully. 
[link](https://kie.zulipchat.com/#narrow/stream/232677-drools/topic/Faulty.20implementation.20of.20verify.20method.20in.20KieHelper)
<details>
<summary>
</summary> …
=> [DROOLS-6487] Write KieModuleModel to KieFileSystem when verifying

kie-internal/src/main/java/org/kie/internal/task/api/model/TaskEvent.java
**[JBPM-9882](https://issues.redhat.com/browse/JBPM-9882)**: Adding actual owner to TaskEvent
<details>
<summary>
</summary>
</details>
=> [JBPM-9882] Adding actual owner to TaskEvent

kie-api/src/build/revapi-config.json, kie-api/src/main/java/org/kie/api/executor/ExecutorService.java, kie-api/src/main/java/org/kie/api/executor/ExecutorStoreService.java
Jira: https://issues.redhat.com/browse/JBPM-9900
Cherry-pick https://github.com/kiegroup/droolsjbpm-knowledge/commit/45f5aaf99a3bafb66670bc244e5202e561e68702
=> (GSS) [7.59.x] [JBPM-9900] RequestInfo.owner is null even if "org.kie.executor.id" is defined

kie-internal/src/main/java/org/kie/internal/query/QueryParameterIdentifiers.java, kie-internal/src/main/java/org/kie/internal/runtime/manager/audit/query/ExecutionErrorInfoDeleteBuilder.java
Created ExecutionErrorInfoDeleteBuilder.
https://github.com/kiegroup/jbpm/pull/2104 depends on this PR.
JIRA: https://issues.redhat.com/browse/JBPM-9992
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or …
=> JBPM-9992 Created ExecutionErrorInfoDeleteBuilder

kie-archetypes/kie-service-spring-boot-archetype/README.md, kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/META-INF/archetype-post-generate.groovy, kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/archetype-resources/pom.xml, kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/archetype-resources/src/main/resources/application-dev.properties, kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/archetype-resources/src/main/resources/application-mysql.properties, kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/archetype-resources/src/main/resources/application-postgres.properties, kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/archetype-resources/src/main/resources/application.properties
**[JBPM-9862](https://issues.redhat.com/browse/JBPM-9862)**: Add swagger config support into kie-service-spring-boot-archetype
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions …
=> [JBPM-9862] - Add swagger config support into kie-service-spring-boot-archetype

kie-internal/src/main/java/org/kie/internal/runtime/manager/InternalRuntimeManager.java
Jira: https://issues.redhat.com/browse/JBPM-10016
singleton is not covered when there is runtime because there is no context mapping associated.
=> [JBPM-10016] Drools/jBPM integration: high number of instances waiting for signal adversely impacts execution time
