kie-docs/dashbuilder-docs/src/main/docbook/en-US/ImportExport.xml
kie-docs/dashbuilder-docs/src/main/docbook/en-US/ImportExport/DataSources.xml
kie-docs/dashbuilder-docs/src/main/docbook/en-US/ImportExport/KPI.xml
kie-docs/dashbuilder-docs/src/main/docbook/en-US/ImportExport/Workspaces.xml

Fixing some typos and wording problems as well as some factual mistakes.

Fix some import/export dashbuilder doc mistakes/typos

---

kie-internal/src/main/java/org/kie/internal/remote/PermissionConstants.java

See: https://issues.jboss.org/browse/JBPM-4741
Also see: 
- droolsjbpm/guvnor/pull/153
- droolsjbpm/droolsjbpm-integration/pull/173
- droolsjbpm/kie-wb-distributions/pull/91
Please rebase this PR to preserve a linear history! :)

JBPM-4741 - Adding roles to to control access to the REST API

---

kie-api/src/main/resources/org/kie/api/kmodule.xsd

Comments to help users find the XSD's + to prevent our build guys from making mistakes + add a TODO

DROOLS-1019 Comments

---

kie-api/pom.xml
kie-internal/pom.xml
pom.xml

Depends on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/207

kie-parent now brings all 3rd party deps

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/KieServices.java
kie-api/src/main/java/org/kie/api/management/GAV.java
kie-api/src/main/java/org/kie/api/management/KieContainerMonitorMXBean.java

Perform necessary Public KIE API changes for allowing API users to
specify an optional, unique, container ID.

DROOLS-1235 MBean naming rework

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/task/TaskService.java
kie-internal/src/main/java/org/kie/internal/task/api/InternalTaskService.java
kie-internal/src/main/java/org/kie/internal/task/api/TaskQueryService.java

Related to the release this week. 
PR Set: 
- https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/160
- https://github.com/droolsjbpm/jbpm/pull/560
- https://github.com/droolsjbpm/droolsjbpm-integration/pull/605

[6.4x] RHBPMS-4184,JBPM-5277 - getTasksAssignedAsPotentialOwner doesn't allow groups searching, only actorid

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/task/TaskService.java
kie-internal/src/main/java/org/kie/internal/task/api/InternalTaskService.java
kie-internal/src/main/java/org/kie/internal/task/api/TaskQueryService.java

PR Set: 
- https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/161
- https://github.com/droolsjbpm/jbpm/pull/561
- https://github.com/droolsjbpm/droolsjbpm-integration/pull/606

[6.5.x] RHBPMS-4184,JBPM-5277 - getTasksAssignedAsPotentialOwner doesn't allow groups searching, only actorid

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/command/KieCommands.java

@mariofusco @etirelli could you please have a look

DROOLS-1270 - support fact handle operations for REST APIs on kie server

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/command/KieCommands.java

(cherry picked from commit ffaab9de0a09240b7b23ff5422a35be61fc2bce7)

[6.5.x] DROOLS-1270 - support fact handle operations for REST APIs on kie server

---

kie-api/src/main/java/org/kie/api/runtime/process/CaseAssignment.java

JBPM-4646 - Case management - simplified use for case role assignments

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/task/TaskLifeCycleEventListener.java
kie-api/src/main/java/org/kie/api/task/UserGroupCallback.java
kie-internal/src/main/java/org/kie/internal/task/api/UserGroupCallback.java

@krisv @psiroky could you please have a look

Cleanup api - JBPM-5293, JBPM-5383

---

kie-api/pom.xml

Hi, @psiroky,
I have just found that nonBreaking changes were not included in reports. Now it should be OK.
Thanks for merging!
Marian

Include nonBreaking changes in revapi report

---

kie-api/src/main/java/org/kie/api/runtime/KieContainer.java

@mariofusco could you please quickly review this?

Clarify the usage of KieContainer#updateToVersion()

---

kie-api/pom.xml
kie-api/src/build/revapi-config.json

Hi,
I have added a couple of ignores because of upgrading revapi to 0.8.1 version.
Thanks,
Marian

Add new ignores because of 0.8.1 version

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/task/TaskService.java
kie-internal/src/main/java/org/kie/internal/task/api/InternalTaskService.java
kie-internal/src/main/java/org/kie/internal/task/api/TaskQueryService.java

Changes for [JBPM-5296](https://issues.jboss.org/browse/JBPM-5296) within kie-api.
PR set
#199
droolsjbpm/jbpm#725

JBPM-5296 - Cleaning up human-task and removing deprecated code

---

kie-internal/src/main/java/org/kie/internal/task/api/assignment/Assignment.java
kie-internal/src/main/java/org/kie/internal/task/api/assignment/AssignmentStrategy.java

@krisv whenever you have time ... hopefully before 2018...

JBPM-5591 - Pluggable task assignment

---

kie-api/src/main/java/org/kie/api/io/ResourceType.java
kie-api/src/main/java/org/kie/api/runtime/conf/BeliefSystemTypeOption.java
kie-api/src/main/java/org/kie/api/runtime/conf/ClockTypeOption.java
kie-api/src/main/java/org/kie/api/runtime/conf/TimerJobFactoryOption.java
kie-api/src/main/java/org/kie/api/runtime/conf/WorkItemHandlerOption.java
kie-internal/src/main/java/org/kie/internal/builder/ResourceChange.java
kie-internal/src/main/java/org/kie/internal/builder/ResourceChangeSet.java
kie-internal/src/main/java/org/kie/internal/builder/conf/AccumulateFunctionOption.java
kie-internal/src/main/java/org/kie/internal/builder/conf/DefaultDialectOption.java
kie-internal/src/main/java/org/kie/internal/builder/conf/DefaultPackageNameOption.java
kie-internal/src/main/java/org/kie/internal/builder/conf/DumpDirOption.java
kie-internal/src/main/java/org/kie/internal/builder/conf/EvaluatorOption.java
kie-internal/src/main/java/org/kie/internal/builder/conf/KBuilderSeverityOption.java
kie-internal/src/main/java/org/kie/internal/conf/AlphaThresholdOption.java
kie-internal/src/main/java/org/kie/internal/conf/CompositeKeyDepthOption.java
kie-internal/src/main/java/org/kie/internal/conf/ConsequenceExceptionHandlerOption.java
kie-internal/src/main/java/org/kie/internal/conf/ConstraintJittingThresholdOption.java
kie-internal/src/main/java/org/kie/internal/conf/MaxThreadsOption.java
kie-internal/src/main/java/org/kie/internal/conf/PermGenThresholdOption.java
kie-internal/src/main/java/org/kie/internal/runtime/conf/NamedObjectModel.java
kie-internal/src/main/java/org/kie/internal/runtime/conf/ObjectModel.java
kie-internal/src/main/java/org/kie/internal/task/api/assignment/Assignment.java
kie-internal/src/main/java/org/kie/internal/utils/ChainedProperties.java

For more details see https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/374

Fix missing curly braces around code blocks.

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/runtime/conf/TimedRuleExecutionOption.java

Seizing the chance of major release to fix the typing mistake.
Other PRs will follow in their relevant repositories to align for the same, including docs:

DROOLS-1244 TimedRuleExectionOption typing mistake

---

kie-api/src/main/java/org/kie/api/runtime/query/AdvancedQueryContext.java

Enhancing the advanced queries provided by REST and JMS to support a full SQL ORDER BY clause. This ensures the sort order can be selected per column of ordering.

JBPM-5468 - Enable multiple column sorting on advanced queries

---

kie-api/src/build/revapi-config.json

Hi, @psiroky,
same as #228, but for 7.0.x.
Marian

[7.0.x] Change revapi-config.json comment to be more general

---

kie-api/src/main/java/org/kie/api/builder/ReleaseId.java
kie-api/src/main/java/org/kie/api/builder/ReleaseIdComparator.java
kie-api/src/main/java/org/kie/api/runtime/KieContainer.java

GUVNOR-3025: OpenShift S2I (Source to Image) Integration
https://issues.jboss.org/browse/GUVNOR-3025

GUVNOR-3025: OpenShift S2I (Source to Image) Integration

---

kie-api/src/main/java/org/kie/api/builder/ReleaseIdComparator.java
kie-api/src/main/resources/org/kie/api/KieAPI.gwt.xml

Remove references to Locale and Properties classes, and the localized lowercasing
https://issues.jboss.org/browse/GUVNOR-3025

Remove references to Locale and Properties classes, and the localized lowercasing

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/command/KieCommands.java
kie-internal/src/main/java/org/kie/internal/command/CommandFactory.java

(cherry picked from commit 74f3104bd3e592ae98c0a15bb31c6608c1fc2d1c)

[JBPM-5019] DisposeCommand is not part of the public API

---

kie-api/src/main/java/org/kie/api/internal/utils/ServiceDiscoveryImpl.java

DROOLS-2122 skip service entry when Properties.load a Drools v6 kie.conf

---

kie-api/src/main/java/org/kie/api/executor/ExecutorService.java

Companion to https://github.com/kiegroup/kie-docs/pull/685 - cleanup of unused system properties.
@mswiderski please check

Remove unused sys. prop. org.uberfire.cluster.local.id

---

kie-api/src/main/java/org/kie/api/internal/utils/ServiceDiscoveryImpl.java
kie-api/src/test/java/org/kie/api/internal/utils/MockAssemblersImpl.java
kie-api/src/test/java/org/kie/api/internal/utils/MockChildAssemblerService.java
kie-api/src/test/java/org/kie/api/internal/utils/ServiceDiscoveryImplTest.java
kie-api/src/test/resources/META-INF/kie.conf

The proposed change is to allow to define multiple services on the same line in kie.conf. 
@mariofusco @etirelli could you please review?

DROOLS-2345 Allow multiple services on same line in kie.conf

---

kie-api/src/main/java/org/kie/api/pmml/PMML4Data.java
kie-api/src/main/java/org/kie/api/pmml/PMML4DataType.java
kie-api/src/main/java/org/kie/api/pmml/PMML4Result.java
kie-api/src/main/java/org/kie/api/pmml/PMMLRequestData.java
kie-api/src/main/java/org/kie/api/pmml/ParameterInfo.java

Backport of kie-pmml code to allow building from pmml resources in workbench

DROOLS-2243_7_5_x

---

kie-api/src/main/java/org/kie/api/pmml/PMMLRequestData.java

Ensemble with:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/726
- https://github.com/kiegroup/jbpm-designer/pull/758
- https://github.com/kiegroup/kie-wb-common/pull/1546
- https://github.com/kiegroup/drools-wb/pull/840

BAQE-400: remove unused imports

---

kie-api/src/main/java/org/kie/api/io/ResourceType.java

depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/762

JBPM-7323 - CMMN excution support for case management

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/runtime/manager/RuntimeEnvironment.java
kie-api/src/main/java/org/kie/api/runtime/manager/RuntimeEnvironmentBuilder.java
kie-api/src/main/java/org/kie/api/task/UserInfo.java

added setUserInfo to the runtime environment

[JBPM-4947] Add userInfo() for RuntimeEnvironmentBuilder to be able to set a custom UserInfo

---

kie-api/src/build/revapi-config.json

depends on kiegroup/droolsjbpm-build-bootstrap#775

Change revapi to check against 7.5.0.Final

---

kie-api/src/main/java/org/kie/api/internal/utils/ServiceDiscoveryImpl.java

random fix from findbugs report on Jenkins CI

adding throw to exception creation

---

kie-api/src/main/java/org/kie/api/internal/utils/ServiceDiscoveryImpl.java

back port of https://github.com/kiegroup/droolsjbpm-knowledge/pull/288

[7.5.x] adding throw to exception creation

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/runtime/builder/ContextFluent.java

@kkufova @Rikkola @mariofusco 
PRs:
https://github.com/kiegroup/drools/pull/2024
https://github.com/kiegroup/droolsjbpm-knowledge/pull/321

[DROOLS-2914] Moved addCommand to public API

---

kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/archetype-resources/src/main/java/DefaultWebSecurityConfig.java

@tsurdilo small addition so business apps can be easily used by workbench's default user wbadmin

added wbadmin to default web security for business apps

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/runtime/process/CaseAssignment.java

depends on
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/861

JBPM-7880 - ElasticSearch event emitter for runtime events

---

kie-internal/src/main/java/org/kie/internal/builder/fluent/DMNFluent.java

NOTE: it cannot be tested via UI yet, only code + tests
@kkufova @Rikkola @gitgabrio 
PR list
https://github.com/kiegroup/drools-wb/pull/1027
https://github.com/kiegroup/drools/pull/2194
https://github.com/kiegroup/droolsjbpm-knowledge/pull/353

[DROOLS-3368] Extend scenario runner to support DMN runtime

---

kie-api/pom.xml
kie-internal/pom.xml

PR set:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/900 (Please comment on this PR if you have any questions)
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/352
* https://github.com/kiegroup/drools/pull/2191
* https://github.com/kiegroup/jbpm/pull/1394
* https://github.com/kiegroup/optaplanner/pull/469
* https://github.com/kiegroup/droolsjbpm-integration/pull/1667
* https://github.com/kiegroup/appformer/pull/574
* https://github.com/kiegroup/optaplanner-wb/pull/319
* https://github.com/kiegroup/jbpm-wb/pull/1257
* https://github.com/kiegroup/kie-wb-distributions/pull/858
* https://github.com/kiegroup/optaweb-employee-rostering/pull/215

Align JAXB and JAXWS APIs with Wildfly

---

kie-internal/pom.xml

Change scope of javax.activation:activation to provided

---

kie-api/src/main/java/org/kie/api/pmml/AbstractOutput.java
kie-api/src/main/java/org/kie/api/pmml/DoubleFieldOutput.java
kie-api/src/main/java/org/kie/api/pmml/IntegerFieldOutput.java
kie-api/src/main/java/org/kie/api/pmml/OutputFieldFactory.java
kie-api/src/main/java/org/kie/api/pmml/PMML4AbstractField.java
kie-api/src/main/java/org/kie/api/pmml/PMML4DataField.java
kie-api/src/main/java/org/kie/api/pmml/PMML4Field.java
kie-api/src/main/java/org/kie/api/pmml/PMML4Output.java
kie-api/src/main/java/org/kie/api/pmml/PMML4OutputField.java
kie-api/src/main/java/org/kie/api/pmml/PMML4Result.java
kie-api/src/main/java/org/kie/api/pmml/StringFieldOutput.java
kie-internal/src/main/java/org/kie/internal/command/ExtendedKieCommands.java

This PR combines the removal of all 'declare' statements from rules generated by PMML, and the addition of support for running containers that include PMML within kie-server, by using the ApplyPmmlModelCommand.

RHDM-766 /  DROOLS-3404

---

kie-api/src/main/java/org/kie/api/io/ResourceType.java
kie-api/src/test/java/org/kie/api/io/ResourceTypeTest.java

Assembly:
https://github.com/kiegroup/drools/pull/2257
https://github.com/kiegroup/droolsjbpm-knowledge/pull/370
https://github.com/kiegroup/jbpm/pull/1440

JBPM-8166: case modeler - register the assets into the workbench and process engine

---

kie-api/src/main/java/org/kie/api/io/ResourceType.java
kie-api/src/test/java/org/kie/api/io/ResourceTypeTest.java

Assembly:
#374 
kiegroup/kie-wb-common#2477

JBPM-8165: provide the ability to generate task forms

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/pmml/PMML4Result.java

RHPAM-1900 Added XStream marshalling/unmarshalling of PMML API objects

Fixes to allow XStream processing of PMML related objects

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/pmml/PMML4Result.java

RHPAM-1900 Added XStream marshalling/unmarshalling of PMML API objects

RHPAM-1900 [7.18.x] Fixes to allow XStream processing of PMML related objects

---

kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/META-INF/archetype-post-generate.groovy
kie-internal/src/main/java/org/kie/internal/runtime/error/ExecutionErrorListener.java

Assembly:
- https://github.com/kiegroup/droolsjbpm-integration/pull/1799
- https://github.com/kiegroup/jbpm/pull/1473
- https://github.com/kiegroup/kie-soup/pull/84
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/379

JBPM-8347 - Add execution error listeners

---

kie-api/src/main/resources/change-set-1.0.0.xsd
kie-api/src/main/resources/change-set.xsd

[DROOLS-4085] Added change set xsd to avoid fetching it from the internet

---

kie-api/src/build/revapi-config.json

depends on kiegroup/droolsjbpm-build-bootstrap#1002

BAQE-1039 - Change revapi to check against 7.23.0.Final

---

kie-internal/src/main/java/org/kie/internal/task/api/prediction/PredictionOutcome.java
kie-internal/src/main/java/org/kie/internal/task/api/prediction/PredictionService.java

Adding prediction service API and prediction result type.

[BAPL-1123] Add prediction service integration

---

kie-api/src/build/revapi-config.json

depends on kiegroup/droolsjbpm-build-bootstrap#1070

BAQE-1114 - Change revapi to check against 7.26.0.Final

---

kie-api/src/main/resources/org/kie/api/kmodule.xsd
kie-api/src/main/resources/org/kie/api/old-kmodule.xsd
kie-api/src/test/resources/org/kie/api/kmod1.xml

Signed-off-by: Filippe Spolti <fspolti@redhat.com>

[DROOLS-4513] - s2i build fails at KieServerContainerVerifier

---

kie-internal/src/main/java/org/kie/internal/ruleunit/RuleUnitDescription.java

see https://github.com/kiegroup/drools/pull/2678

DROOLS-4850: ModelCompiler, rm RuleUnitDescription.getRuleUnitClass()

---

kie-internal/src/main/java/org/kie/internal/ruleunit/RuleUnitComponentFactory.java

Reverts kiegroup/droolsjbpm-knowledge#418

Revert "[KOGITO-432] allow to declare RuleUnit data sources in drl"

---

kie-internal/src/main/java/org/kie/internal/builder/fluent/KieContainerFluent.java

@yesamer @gitgabrio @dupliaka @jomarko 
Minor API update
https://issues.redhat.com/browse/DROOLS-4878
PRs:
- https://github.com/kiegroup/drools/pull/2700
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/417

[DROOLS-4878] Test Scenario: fix support for default stateless kieSession

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/builder/KieBuilder.java
kie-internal/src/main/java/org/kie/internal/utils/KieHelper.java

https://github.com/kiegroup/droolsjbpm-integration/pull/1864
https://github.com/kiegroup/drools/pull/2636
https://github.com/kiegroup/openshift-drools-hacep/pull/68
https://github.com/kiegroup/kie-wb-playground/pull/78
https://github.com/kiegroup/droolsjbpm-knowledge/pull/397

 [DROOLS-4092] Default to executable model in the kie-maven-plugin

---

kie-internal/src/main/java/org/kie/internal/builder/conf/ExternaliseCanonicalModelLambdaOption.java

(cherry picked from commit 8733aabc99e663292d54b4e036ffed13e0a94c98)

[DROOLS-5105] lambda externalisation default to false

---

kie-internal/src/main/java/org/kie/internal/utils/KieHelper.java

See unit test https://github.com/kiegroup/drools/pull/2845

[DROOLS-5149] Able to specify a releaseId with KieHelper

---

kie-internal/src/main/java/org/kie/internal/task/api/InternalTaskService.java

added new for impersonated another user when saving content

[RHPAM-2813] Allow to use 'user' query parameter with /contents/output REST API.

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/definition/process/Node.java
kie-api/src/main/java/org/kie/api/definition/process/NodeContainer.java
kie-api/src/main/java/org/kie/api/runtime/KieSession.java
kie-api/src/main/java/org/kie/api/runtime/manager/audit/NodeInstanceLog.java
kie-api/src/main/java/org/kie/api/runtime/process/ProcessRuntime.java
kie-internal/src/main/java/org/kie/internal/process/CorrelationAwareProcessRuntime.java

Adding interfaces to support restart process

[JBPM-9129] Start process without triggering a start node

---

kie-api/src/main/java/org/kie/api/io/ResourceType.java
kie-api/src/main/java/org/kie/api/pmml/PMMLConstants.java

@mariofusco @danielezonca 
See https://issues.redhat.com/browse/DROOLS-5372 https://issues.redhat.com/browse/DROOLS-5417.
This PR simply create a new NO_OP ResourceType.

[DROOLS-5417] Implement "NOOP" ResourceType

---

kie-api/src/build/revapi-config.json

depends on kiegroup/droolsjbpm-build-bootstrap#1404

BAQE-1488 - Change revapi to check against 7.39.0.Final

---

kie-api/src/main/java/org/kie/api/task/UserGroupCallback.java
kie-api/src/main/java/org/kie/api/task/model/Email.java
kie-internal/src/main/java/org/kie/internal/task/api/TaskModelFactory.java
kie-internal/src/main/java/org/kie/internal/task/api/TaskPersistenceContext.java

allow arbitrary emails notifications through parameter toemails

[JBPM-9197] Allow the introduction of emails in Tasks notifications

---

kie-archetypes/kie-kjar-archetype/README.md
kie-archetypes/kie-model-archetype/README.md
kie-archetypes/kie-service-spring-boot-archetype/README.md

some missing version updates in READMEs

upgraded version to 7.42.0-SNAPSHOT

---

kie-api/src/main/java/org/kie/api/KieServices.java

Reverts kiegroup/droolsjbpm-knowledge#443

Revert "[JBPM-9178] Immutable SpringBoot Deployment"

---

kie-api/src/main/java/org/kie/api/fluent/ActionNodeBuilder.java
kie-api/src/main/java/org/kie/api/fluent/BoundaryEventNodeBuilder.java
kie-api/src/main/java/org/kie/api/fluent/CompositeNodeBuilder.java
kie-api/src/main/java/org/kie/api/fluent/CompositeNodeOperations.java
kie-api/src/main/java/org/kie/api/fluent/Dialect.java
kie-api/src/main/java/org/kie/api/fluent/DynamicNodeBuilder.java
kie-api/src/main/java/org/kie/api/fluent/EndNodeBuilder.java
kie-api/src/main/java/org/kie/api/fluent/EventNodeBuilder.java
kie-api/src/main/java/org/kie/api/fluent/EventNodeOperations.java
kie-api/src/main/java/org/kie/api/fluent/FaultNodeBuilder.java
kie-api/src/main/java/org/kie/api/fluent/ForEachNodeBuilder.java
kie-api/src/main/java/org/kie/api/fluent/HumanNodeOperations.java
kie-api/src/main/java/org/kie/api/fluent/HumanTaskNodeBuilder.java
kie-api/src/main/java/org/kie/api/fluent/JoinNodeBuilder.java
kie-api/src/main/java/org/kie/api/fluent/MilestoneNodeBuilder.java
kie-api/src/main/java/org/kie/api/fluent/NodeBuilder.java
kie-api/src/main/java/org/kie/api/fluent/NodeContainerBuilder.java
kie-api/src/main/java/org/kie/api/fluent/ProcessBuilder.java
kie-api/src/main/java/org/kie/api/fluent/ProcessBuilderFactories.java
kie-api/src/main/java/org/kie/api/fluent/ProcessBuilderFactory.java
kie-api/src/main/java/org/kie/api/fluent/RuleSetNodeBuilder.java
kie-api/src/main/java/org/kie/api/fluent/SplitNodeBuilder.java
kie-api/src/main/java/org/kie/api/fluent/StartNodeBuilder.java
kie-api/src/main/java/org/kie/api/fluent/SubProcessNodeBuilder.java
kie-api/src/main/java/org/kie/api/fluent/TimerNodeBuilder.java
kie-api/src/main/java/org/kie/api/fluent/TimerOperations.java
kie-api/src/main/java/org/kie/api/fluent/Variable.java
kie-api/src/main/java/org/kie/api/fluent/WorkItemNodeBuilder.java
kie-api/src/main/java/org/kie/api/fluent/package-info.java

Adding new  org.kie.api.fluent package container official fluent API
**JIRA**: 
[JBPM-9287](https://issues.redhat.com/browse/JBPM-9287)

[JBPM-9287] Adding official support for fluent API

---

kie-api/src/main/java/org/kie/api/KieServices.java

Jira
https://issues.redhat.com/browse/JBPM-9178

[JBPM-9178] Immutable SpringBoot Deployment

---

kie-internal/src/main/java/org/kie/internal/identity/IdentityProvider.java

JIRA:
https://issues.redhat.com/browse/JBPM-9317

[JBPM-9317] userTaskService.saveContent doesn't work

---

kie-api/src/build/revapi-config.json

**JIRA**: [BAQE-1567](https://issues.redhat.com/browse/BAQE-1567)
depends on kiegroup/droolsjbpm-build-bootstrap#1485

BAQE-1567 - Change revapi to check against 7.44.0.Final

---

kie-api/src/main/java/org/kie/api/internal/utils/ServiceDiscoveryImpl.java

See https://issues.redhat.com/browse/DROOLS-5722

[DROOLS-5722] Fix ServiceDiscoveryImpl.reset()

---

kie-internal/src/main/java/org/kie/internal/builder/conf/AlphaNetworkCompilerOption.java

https://issues.redhat.com/browse/DROOLS-5658
https://issues.redhat.com/browse/DROOLS-4844
[link](https://www.example.com)
**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1498
https://github.com/kiegroup/drools/pull/3159
https://github.com/kiegroup/droolsjbpm-knowledge/pull/471
https://github.com/kiegroup/droolsjbpm-integration/pull/2277
<details>
<summary>
</summary>
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run …

[DROOLS-5658] Descope Alpha Network Compiler

---

kie-api/src/main/java/org/kie/api/KieBaseConfiguration.java
kie-internal/src/main/java/org/kie/internal/conf/AlphaRangeIndexThresholdOption.java

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-5647
https://github.com/kiegroup/drools/pull/3145
<details>
<summary>
</summary>
</details>

[DROOLS-5647] Add range indexing to AlphaNode

---

kie-api/src/main/java/org/kie/api/event/process/MessageEvent.java
kie-api/src/main/java/org/kie/api/event/process/ProcessEventListener.java
kie-api/src/main/java/org/kie/api/event/process/SignalEvent.java

Adding listener for signal and messages
**JIRA**: 
[JBPM-9474](https://issues.redhat.com/browse/JBPM-9474)
https://github.com/kiegroup/jbpm/pull/1808
https://github.com/kiegroup/drools/pull/3264
https://github.com/kiegroup/droolsjbpm-integration/pull/2322

[JBPM-9474] Produce events to Kafka by Signal or Messages Events

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/command/KieCommands.java
kie-api/src/main/java/org/kie/api/pmml/PMMLImplementationsUtil.java
kie-internal/src/main/java/org/kie/internal/command/ExtendedKieCommands.java
kie-internal/src/main/java/org/kie/internal/pmml/PMMLCommandExecutor.java
kie-internal/src/main/java/org/kie/internal/pmml/PMMLCommandExecutorFactory.java
kie-internal/src/main/java/org/kie/internal/pmml/PMMLImplementationsUtil.java
kie-internal/src/test/java/org/kie/internal/pmml/PMMLImplementationsUtilTest.java

See https://issues.redhat.com/browse/DROOLS-5867

[Drools 5867] - Update ApplyPmmlModelCommand to manage both PMML implementations

---

kie-api/src/main/java/org/kie/api/cluster/ClusterAwareService.java
kie-api/src/main/java/org/kie/api/cluster/ClusterListener.java
kie-api/src/main/java/org/kie/api/cluster/ClusterNode.java
kie-api/src/main/java/org/kie/api/internal/utils/ServiceRegistry.java

Jira: https://issues.redhat.com/browse/JBPM-9399
Add interface of cluster aware service

[JBPM-9399] Add support to jBPM and runtime/cluster environments detection

---

kie-internal/src/main/java/org/kie/internal/pmml/PMMLImplementationsUtil.java
kie-internal/src/test/java/org/kie/internal/pmml/PMMLImplementationsUtilTest.java

[Revert_PMML_Default] Reverting default to Legacy

---

kie-api/src/main/java/org/kie/api/runtime/rule/AccumulateFunction.java

**JIRA**: https://issues.redhat.com/browse/DROOLS-5953
Related PR: https://github.com/kiegroup/drools/pull/3328

[DROOLS-5953] generalize accumulate function

---

kie-internal/src/main/java/org/kie/internal/pmml/PMMLCommandExecutor.java

See https://issues.redhat.com/browse/DROOLS-5861
Needed by
https://github.com/kiegroup/drools/pull/3296
https://github.com/kiegroup/kogito-runtimes/pull/973

[DROOLS-5861] Propagating Context in PMMLCommandExecutor.execute

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/builder/model/KieBaseModel.java
kie-api/src/main/java/org/kie/api/conf/BetaRangeIndexOption.java
kie-api/src/main/resources/org/kie/api/kmodule.xsd

- Adding BetaRangeIndexOption
**JIRA**: 
https://issues.redhat.com/browse/DROOLS-5910
<details>
<summary>
</summary>
</details>

[DROOLS-5910] Enable range index for JoinNode

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/internal/assembler/KieAssemblerService.java
kie-api/src/main/java/org/kie/api/internal/assembler/KieAssemblers.java
kie-api/src/test/java/org/kie/api/internal/utils/MockAssemblersImpl.java
kie-internal/src/main/java/org/kie/internal/services/KieAssemblersImpl.java

**JIRA**: https://issues.redhat.com/browse/DROOLS-5950
- https://github.com/kiegroup/drools/pull/3335
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/497

DROOLS-5950 Support returning PackageDescr from assemblers

---

kie-api/src/main/java/org/kie/api/runtime/conf/ClockTypeOption.java
kie-api/src/main/java/org/kie/api/runtime/rule/QueryResults.java
kie-internal/src/main/java/org/kie/internal/ruleunit/RuleUnitDescription.java
kie-internal/src/main/java/org/kie/internal/ruleunit/RuleUnitVariable.java

**JIRA**: https://issues.redhat.com/browse/DROOLS-6007

[DROOLS-6007] changes to enable improvements to Kogito API

---

kie-internal/src/main/java/org/kie/internal/command/CommandFactory.java

**JIRA**: https://issues.redhat.com/browse/DROOLS-6037
**referenced Pull Requests**: none
<details>
<summary>
</summary>
</details>

DROOLS-6037 Align correct error message

---

kie-api/src/main/java/org/kie/api/internal/assembler/KieAssemblerService.java

@danielezonca @afalhambra  @jiripetrlik
See https://issues.redhat.com/browse/DROOLS-6062

[DROOLS-6062] Fix default methods management inside KieAssemblerService

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/builder/model/KieSessionModel.java
kie-api/src/main/java/org/kie/api/runtime/conf/DirectFiringOption.java
kie-api/src/main/resources/org/kie/api/kmodule.xsd

**JIRA**: https://issues.redhat.com/browse/DROOLS-6086

[DROOLS-6086] allow direct firing from rule terminal node

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/builder/model/KieSessionModel.java
kie-api/src/main/java/org/kie/api/runtime/conf/ThreadSafeOption.java
kie-api/src/main/resources/org/kie/api/kmodule.xsd

**JIRA**: https://issues.redhat.com/browse/DROOLS-6087

[DROOLS-6087] add KieSession option to flag it as non-thread-safe

---

kie-internal/src/main/java/org/kie/internal/builder/conf/ParallelLambdaExternalizationOption.java

**JIRA**: _(please edit the JIRA link if it exists)_ 
https://issues.redhat.com/browse/DROOLS-6327
**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
https://github.com/kiegroup/droolsjbpm-knowledge/pull/516
https://github.com/kiegroup/kie-benchmarks/pull/115
https://github.com/kiegroup/drools/pull/3591
https://github.com/kiegroup/kie-docs/pull/3539
<details>
<summary>
</summary>
* <b>a full production downstream build</b> …

[DROOLS-6327] Parallel Lambda Externalization

---

kie-internal/src/main/java/org/kie/internal/runtime/manager/deploy/DeploymentDescriptorManager.java

Fixing null pointer when there is not deployment descriptor at the specified location
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9727)

[JBPM-9727] NullPointerException while doing the project deployment

---

README.md
kie-internal/src/main/java/org/kie/internal/runtime/conf/MergeMode.java
kie-internal/src/test/java/org/kie/internal/runtime/manager/deploy/DeploymentDescriptorMergerTest.java
pom.xml

**JIRA**: https://issues.redhat.com/browse/DROOLS-6422

[DROOLS-6422] fix droolsjbpm-knowledge wording

---

kie-internal/src/main/java/org/kie/internal/utils/KieHelper.java

**JIRA**: _(please edit the JIRA link if it exists)_ 
[DROOLS-6458](https://issues.redhat.com/browse/DROOLS-6458)

DROOLS-6458 Allow KieHelper to build model-based DRL from configuration

---

kie-internal/src/main/java/org/kie/internal/builder/ResourceChangeSet.java

**JIRA**: https://issues.redhat.com/browse/DROOLS-6557

[DROOLS-6557] add package to ResourceChangeSet

---

.github/pull_request_template.md

**JIRA**: _(please edit the JIRA link if it exists)_ 
[link](https://www.example.com)
**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
* paste the link(s) from GitHub here
* link 2
* link 3 etc.
<details>
<summary>
</summary>
</details>

Add note for 7.x branch

---

kie-internal/src/main/java/org/kie/internal/builder/fluent/ContextFluent.java

JIRA: https://issues.redhat.com/browse/DROOLS-6683

[DROOLS-6683] improve ContextImpl constructor performance

---

kie-api/src/main/java/org/kie/api/project/KieActivator.java

**JIRA**:  
[https://issues.redhat.com/browse/KOGITO-795](https://issues.redhat.com/browse/KOGITO-795)
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/575
* https://github.com/kiegroup/kogito-tooling/pull/647
<details>
<summary>
</summary>
</details>

KOGITO-795: Added KieActivator for Language Server based projects

---

kie-api/src/build/revapi-config.json
kie-api/src/main/java/org/kie/api/task/TaskService.java
kie-internal/src/main/java/org/kie/internal/task/api/TaskInstanceService.java

Jira: https://issues.redhat.com/browse/JBPM-10015

[JBPM-10015] Allow to set suspendUntil during user task suspend operation as parameter.

---

kie-archetypes/kie-service-spring-boot-archetype/README.md
kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/META-INF/archetype-post-generate.groovy
kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/archetype-resources/pom.xml
kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/archetype-resources/src/main/resources/application-dev.properties
kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/archetype-resources/src/main/resources/application-mysql.properties
kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/archetype-resources/src/main/resources/application-postgres.properties
kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/archetype-resources/src/main/resources/application.properties

Backport of https://github.com/kiegroup/droolsjbpm-knowledge/pull/590

[7.59.x][JBPM-9862] - Add swagger config support into kie-service-spring-boot-archetype

---

kie-api/src/build/revapi-config.json

**JIRA**: [BAQE-2253](https://issues.redhat.com/browse/BAQE-2253)
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1925
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github …

[7.67.x] BAQE-2253 - Change revapi to check against 7.59.0.Final

---

kie-internal/src/main/java/org/kie/internal/identity/IdentityProvider.java

Jira: https://issues.redhat.com/browse/JBPM-10045

[JBPM-10045] Incorrect response for REST service when "org.kie.server bypass.auth.user" used with Spring Boot Runtime

---

kie-archetypes/kie-drools-archetype/src/main/resources/archetype-resources/src/test/java/RuleTest.java
kie-archetypes/kie-drools-archetype/src/test/resources/projects/integrationtestDefaults/reference/src/test/java/it/pkg/RuleTest.java
kie-archetypes/kie-drools-archetype/src/test/resources/projects/integrationtestWithCEP/reference/src/test/java/it/pkg/RuleTest.java
kie-archetypes/kie-drools-archetype/src/test/resources/projects/integrationtestWithEclipse/reference/src/test/java/it/pkg/RuleTest.java

Backport from https://github.com/kiegroup/drools/pull/4424
**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6990
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case …

[DROOLS-6990] Add dispose in archetypes example codes

---

kie-api/src/main/java/org/kie/api/pmml/PMML4Result.java
kie-internal/src/main/java/org/kie/internal/security/KiePolicyHelper.java

**JIRA**: https://issues.redhat.com/browse/DROOLS-6997
**referenced Pull Requests**: none
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change …

DROOLS-6997 Move printStackTrace() to SLF4J logging

---

kie-internal/src/main/java/org/kie/internal/identity/IdentityProvider.java

Jira: https://issues.redhat.com/browse/JBPM-10045

[7.67.x] [JBPM-10045] Incorrect response for REST service when "org.kie.serverbypass.auth.user" used with Spring Boot Runtime

---

kie-internal/src/main/java/org/kie/internal/identity/IdentityProvider.java

Jira: https://issues.redhat.com/browse/JBPM-10045

[7.67.x-blue] [JBPM-10045] Incorrect response for REST service when "org.kie.serverbypass.auth.user" used with Spring Boot Runtime
